# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_homesong'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homesong',
            name='album',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='HomeSong',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
